##Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
##
##1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##
##By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms



##n1 = 1
##n2 = 1
##count = 1
##Sum = 0
##while count <11:
##       nth = n1 + n2
##       n1 = n2 
##       n2 = nth 
##       count += 1
##       print(n1)
##       if n1%2 == 0:
##              Sum = Sum + n1
##print(Sum)

fib = 1
fib2 = 2
temp = 0
total = 0

while temp <=4000000:
    temp = fib2
    if temp % 2 == 0:
        total += temp
    temp = fib + fib2
    fib = fib2
    fib2 = temp

print ("n =",total)
